package br.com.celsoneto.GerenciadorDeFuncionarios.Funcionarios;

public enum CargoFuncionario {

    VENDEDOR,
    CAIXA,
    GERENTE,
    SUBGERENTE,
    SUPERVISOR,
    AUXILIAR_ADMINISTRATIVO,
    AUXILIAR_DE_ESTOQUE,
    ESTOQUISTA,
    REPOSITOR,
    OPERADOR_DE_CAIXA,
    FISCAL_DE_LOJA,
    ATENDENTE,
    PROMOTOR_DE_VENDAS,
    BALCONISTA,
    ZELADOR,
    AUXILIAR_DE_LIMPEZA,
    SEGURANCA,
    VIGILANTE,
    MANUTENCAO,
    ENCARREGADO,
    CONFERENTE,
    RECEPCIONISTA,
    MOTORISTA,
    ENTREGADOR,
    EMBALADOR,
    CONSULTOR_DE_VENDAS,
    VISUAL_MERCHANDISER,
    ANALISTA_DE_ESTOQUE,
    COORDENADOR_DE_LOJA
}
